name: Docker Workflow

on: 
  push:
    branches:
      - main
      - feature-branchA

jobs: 
 docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build Docker file
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}:${{ github.sha }}

      - name: Test Docker image
        run: |  
          docker images
          docker run --rm --name solar-system-app -d \
          -p 3000:3000 \
          -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
          -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
          -e MONGO_URI=${{ secrets.MONGO_URI }} \
          ${{ vars.DOCKER_USERNAME }}:${{ github.sha }} npm test
      
