name: Solar System Terraform Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-branchA

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest 
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: hashicorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init 
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply or Destroy
        run:  |
         if [ "${{ github.event.inputs.destroy }}" = "yes" ]; then
         terraform destroy -auto-approve
         else
          terraform apply -auto-approve
         fi
        working-directory: ./terraform
