name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-branchA

env:
  MONGO_URI: ${{ vars.MONGO_URI}}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest ,windows-latest]
        nodejs-version: [18, 19, 20]

        exclude:
          - os: macos-latest
            nodejs-version: 18

    runs-on: ${{ matrix.os }}

    steps: 
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js version - ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: nodejs-unit-testing-run-tests
        run: npm test

      - name: Archive test results
        if: steps.nodejs-unit-testing-run-tests.outcome == 'success' || steps.nodejs-unit-testing-run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: mocha-test-results-${{ matrix.os }}-${{ matrix.nodejs-version }}
          path: test-results.xml
  
  code-coverage:
    name: Code Coverage
    needs: unit-testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run code coverage 
        continue-on-error: true
        run: npm run coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-coverage-results
          path: coverage
          retention-days: 5